import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import Navbar from "./components/Navbar";
import Sectiondivider from "./components/Sectiondivider";
import Shadowtop from "./components/Shadowtop";
import Product from "./components/Product";
import Footer from "./components/Footer";

export default function Home() {

  return (
    <>
      {/* Meta Tags */}
      <Head>
        <title>Aqua Merchant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Navbar></Navbar>
      <main>
        <header>
          <div className={styles.containerHeader}></div>
        </header>
        <Sectiondivider />
        <Shadowtop />
        <Product product={"Fashion"} />
        <Product product={"Gadget"} />
        <Product product={"Luxury"} />
        <div className={styles.adsContainer}>
          <a href="" className={styles.ads}>
            Your ads here
          </a>
          <div className={styles.adsDivider}></div>
          <a href="" className={styles.ads}>
            Your ads here
          </a>
        </div>
        <Product product={"Man"} />
        <Product product={"Ladies"} />

        <h3 className={styles.contactMe}>
          If you want website like this
          <br />
          contact developer
        </h3>
        <Footer/>
      </main>
    </>
  );
}
